// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GuestheaderfooterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void guestheaderfooter() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1034, 672));
    driver.findElement(By.cssSelector(".makeStyles-title-5")).click();
    js.executeScript("window.scrollTo(0,18.66666603088379)");
    driver.findElement(By.cssSelector(".sc-dkzDqf:nth-child(1) > .sc-jSMfEi")).click();
    driver.findElement(By.cssSelector(".sc-dkzDqf:nth-child(2) > .sc-jSMfEi")).click();
    driver.findElement(By.linkText("tradingvision@gmail.com")).click();
    driver.findElement(By.linkText("+01 123 456 789")).click();
    driver.findElement(By.linkText("Market")).click();
    driver.findElement(By.linkText("Favorite")).click();
    driver.findElement(By.linkText("Reminder")).click();
    driver.findElement(By.linkText("Facebook")).click();
    driver.findElement(By.linkText("Linkedin")).click();
    driver.findElement(By.linkText("Github")).click();
  }
}
