// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchuserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchuser() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1034, 672));
    driver.findElement(By.cssSelector(".makeStyles-inputInput-9")).click();
    driver.findElement(By.cssSelector(".MuiInputBase-input-55")).click();
    driver.findElement(By.cssSelector(".MuiBackdrop-root")).click();
    driver.findElement(By.cssSelector(".MuiOutlinedInput-input")).click();
    driver.findElement(By.cssSelector(".MuiOutlinedInput-input")).sendKeys("ACB");
    driver.findElement(By.cssSelector(".MuiOutlinedInput-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".MuiContainer-root:nth-child(3)")).click();
  }
}
